/* eslint-disable @typescript-eslint/naming-convention */
export const enum BeehiveVariable {
	BEEHIVE_TOKEN = 'BEEHIVE_TOKEN',
	BEEHIVE_DEFAULT_PREFIX = 'BEEHIVE_DEFAULT_PREFIX',
	BEEHIVE_DEFAULT_LANGUAGE = 'BEEHIVE_DEFAULT_LANGUAGE',
	BEEHIVE_LOWERCASE_COMMANDS = 'BEEHIVE_LOWERCASE_COMMANDS',
	BEEHIVE_BUILTIN_ARGUMENTS = 'BEEHIVE_BUILTIN_ARGUMENTS'
}
