/* eslint-disable @typescript-eslint/naming-convention */
export enum HivenEvents {
	Raw = 'RAW',
	Init = 'init',
	RoomCreate = 'room_create',
	ROOM_CREATE = 'ROOM_CREATE',
	RoomUpdate = 'room_update',
	ROOM_UPDATE = 'ROOM_UPDATE',
	RoomDelete = 'room_delete',
	ROOM_DELETE = 'ROOM_DELETE',
	Message = 'message',
	MESSAGE_CREATE = 'MESSAGE_CREATE',
	MessageUpdate = 'message_update',
	MESSAGE_UPDATE = 'MESSAGE_UPDATE',
	MessageDelete = 'message_delete',
	MESSAGE_DELETE = 'MESSAGE_DELETE',
	TypingStart = 'typing_start',
	TYPING_START = 'TYPING_START',
	HouseJoin = 'house_join',
	HOUSE_JOIN = 'HOUSE_JOIN',
	HouseMemberJoin = 'house_member_join',
	HOUSE_MEMBER_JOIN = 'HOUSE_MEMBER_JOIN',
	HouseMemberLeave = 'house_member_leave',
	HOUSE_MEMBER_LEAVE = 'HOUSE_MEMBER_LEAVE',
	CallCreate = 'call_create',
	CALL_CREATE = 'CALL_CREATE'
}
